### PR TITLE
Fix/wayland

### PR DESCRIPTION
**Pull request by YuanYuYuan**
Hi @scientiac, thanks for your flake! I've tested it and found that I need this modification to run on my laptop.

My environment: 
- Hyprland + Nixos (24.05)
- Asus Zenbook UM5302

### CODE REVIEW

**Comment by scientiac** [comment]
I see that the you have set the default wayland display to 'wayland-1' but normally it is 'wayland-0', so for hyprland, intead of using the default value, I suggest you to specify it in the configuration.

Thanks for the PR

**Comment by YuanYuYuan** [comment]
> I see that the you have set the default wayland display to 'wayland-1' but normally it is 'wayland-0', so for hyprland, intead of using the default value, I suggest you to specify it in the configuration.
> 
> Thanks for the PR

I see. Maybe you can change it to wayland-0 by default and users can specify it accordingly in the option just like you suggested. :)

**Comment by scientiac** [comment]
@YuanYuYuan Thanks, I did exactly that.

**Is the service starting correctly after reboot?**

I have a hit and miss situation and I am having to restart the service manually at times.

**Comment by YuanYuYuan** [comment]
> service

Sorry for the late reply. I was on holiday. Yes, it can work immediately on my laptop without restarting the service.

**Comment by scientiac** [comment]
Now you can switch to using the official repo instead of mine.

**Comment by YuanYuYuan** [comment]
> Now you can switch to using the official repo instead of mine.

Yes. Appreciate your work! :)

**Pull request merged**
